#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "用法：$0 <镜像标签>" >&2
  exit 1
fi

IMAGE_TAG="$1"

if [[ ! "$IMAGE_TAG" =~ ^(sha-[0-9a-f]{12,40}|v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?|V[0-9]{11})$ ]]; then
  echo "[部署] 镜像标签格式错误：$IMAGE_TAG（必须是 sha-<commit>；历史 v/V 标签仅保留兼容）" >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
META_FILE="$ROOT_DIR/release-meta.env"

if [[ ! -f "$META_FILE" ]]; then
  echo "[部署] 缺少配置文件：$META_FILE" >&2
  echo "[部署] 请在 ECS 上创建 release-meta.env，并配置镜像、数据库、登录密钥和管理员账号。" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$META_FILE"
set +a

: "${GHCR_BASE:?请在 release-meta.env 设置 GHCR_BASE}"
: "${POSTGRES_USER:?请在 release-meta.env 设置 POSTGRES_USER}"
: "${POSTGRES_PASSWORD:?请在 release-meta.env 设置 POSTGRES_PASSWORD}"
: "${POSTGRES_DB:?请在 release-meta.env 设置 POSTGRES_DB}"
: "${DATABASE_URL:?请在 release-meta.env 设置 DATABASE_URL}"
: "${COMPOSE_FILE:?请在 release-meta.env 设置 COMPOSE_FILE}"
: "${RUNTIME_ENV_FILE:?请在 release-meta.env 设置 RUNTIME_ENV_FILE}"
: "${METADATA_DIR:?请在 release-meta.env 设置 METADATA_DIR}"

: "${AUTH_TOKEN_SECRET:?请在 release-meta.env 设置 AUTH_TOKEN_SECRET}"
: "${ADMIN_BOOTSTRAP_USERNAME:?请在 release-meta.env 设置 ADMIN_BOOTSTRAP_USERNAME}"
: "${ADMIN_BOOTSTRAP_PASSWORD:?请在 release-meta.env 设置 ADMIN_BOOTSTRAP_PASSWORD}"
: "${ADMIN_BOOTSTRAP_DISPLAY_NAME:?请在 release-meta.env 设置 ADMIN_BOOTSTRAP_DISPLAY_NAME}"

if ! command -v python3 >/dev/null 2>&1; then
  echo "[部署] 缺少 python3，无法校验 DATABASE_URL。" >&2
  exit 1
fi

db_parse_output="$(python3 - <<'PY'
import os
import sys
from urllib.parse import urlparse

db_url = os.environ.get("DATABASE_URL", "")
parsed = urlparse(db_url)

if parsed.scheme not in {"postgresql", "postgres"}:
    print("invalid_scheme")
    sys.exit(0)

db_name = (parsed.path or "").lstrip("/")
print(parsed.username or "")
print(parsed.password or "")
print(parsed.hostname or "")
print(str(parsed.port or ""))
print(db_name)
PY
)"

db_url_user="$(echo "$db_parse_output" | sed -n '1p')"
db_url_password="$(echo "$db_parse_output" | sed -n '2p')"
db_url_host="$(echo "$db_parse_output" | sed -n '3p')"
db_url_port="$(echo "$db_parse_output" | sed -n '4p')"
db_url_name="$(echo "$db_parse_output" | sed -n '5p')"
db_url_password_len="${#db_url_password}"

if [[ "$db_url_user" == "invalid_scheme" ]]; then
  echo "[部署] DATABASE_URL 协议错误，必须是 postgresql:// 或 postgres://" >&2
  exit 1
fi

if [[ -z "$db_url_user" || -z "$db_url_password" || -z "$db_url_host" || -z "$db_url_name" ]]; then
  echo "[部署] DATABASE_URL 缺少关键字段（用户名/密码/主机/库名）。" >&2
  exit 1
fi

if [[ "$db_url_user" != "$POSTGRES_USER" || "$db_url_password" != "$POSTGRES_PASSWORD" || "$db_url_name" != "$POSTGRES_DB" ]]; then
  echo "[部署] DATABASE_URL 与 POSTGRES_* 不一致，已中止部署。" >&2
  echo "[部署] 解析结果：user=$db_url_user host=$db_url_host port=${db_url_port:-5432} db=$db_url_name pass_len=$db_url_password_len" >&2
  echo "[部署] 环境结果：POSTGRES_USER=$POSTGRES_USER POSTGRES_DB=$POSTGRES_DB POSTGRES_PASSWORD_LEN=${#POSTGRES_PASSWORD}" >&2
  exit 1
fi

AUTH_TOKEN_TTL_SECONDS="${AUTH_TOKEN_TTL_SECONDS:-28800}"
EXECUTOR_BASE_URL="${EXECUTOR_BASE_URL:-}"
EXECUTOR_TOKEN="${EXECUTOR_TOKEN:-}"
EXECUTOR_TIMEOUT_SECONDS="${EXECUTOR_TIMEOUT_SECONDS:-20}"
COUPLE_FEATURE_ENABLED="${COUPLE_FEATURE_ENABLED:-false}"
COUPLE_ROUTE="${COUPLE_ROUTE:-/couple/}"
COUPLE_ALLOWED_USERS="${COUPLE_ALLOWED_USERS:-}"
COUPLE_ALLOWED_EMAILS="${COUPLE_ALLOWED_EMAILS:-}"
APP_BASE_URL="${APP_BASE_URL:-}"
SHARE_BASE_URL="${SHARE_BASE_URL:-}"
STORAGE_DRIVER="${STORAGE_DRIVER:-local}"
MAX_UPLOAD_MB="${MAX_UPLOAD_MB:-15}"
WEBDOCK_PHOTO_BASE_URL="${WEBDOCK_PHOTO_BASE_URL:-http://host.docker.internal:11800}"
WEBDOCK_PHOTO_API_TOKEN="${WEBDOCK_PHOTO_API_TOKEN:-}"
WEBDOCK_PHOTO_TIMEOUT_SECONDS="${WEBDOCK_PHOTO_TIMEOUT_SECONDS:-30}"
IMMICH_ENABLED="${IMMICH_ENABLED:-false}"
IMMICH_BASE_URL="${IMMICH_BASE_URL:-}"
IMMICH_API_KEY="${IMMICH_API_KEY:-}"
IMMICH_TIMEOUT_SECONDS="${IMMICH_TIMEOUT_SECONDS:-20}"
IMMICH_PROXY_MODE="${IMMICH_PROXY_MODE:-backend}"
WECOM_ENV_PROFILES="${WECOM_ENV_PROFILES:-}"
WECOM_COMPANY_A_CORP_ID="${WECOM_COMPANY_A_CORP_ID:-}"
WECOM_COMPANY_A_APP_SECRET="${WECOM_COMPANY_A_APP_SECRET:-}"
WECOM_COMPANY_A_APP_SECRET_2="${WECOM_COMPANY_A_APP_SECRET_2:-}"
WECOM_COMPANY_A_APP_SECRETS="${WECOM_COMPANY_A_APP_SECRETS:-}"
WEDOC_COMPANY_A_DOCID="${WEDOC_COMPANY_A_DOCID:-}"
WEDOC_COMPANY_A_SHEET_ID="${WEDOC_COMPANY_A_SHEET_ID:-}"
WEDRIVE_COMPANY_A_SPACEIDS="${WEDRIVE_COMPANY_A_SPACEIDS:-}"
SMARTSHEET_COMPANY_A_ID="${SMARTSHEET_COMPANY_A_ID:-}"
SMARTSHEET_COMPANY_A_SHEET_ID="${SMARTSHEET_COMPANY_A_SHEET_ID:-}"
WECOM_COMPANY_B_CORP_ID="${WECOM_COMPANY_B_CORP_ID:-}"
WECOM_COMPANY_B_APP_SECRET="${WECOM_COMPANY_B_APP_SECRET:-}"
WECOM_COMPANY_B_APP_SECRET_2="${WECOM_COMPANY_B_APP_SECRET_2:-}"
WECOM_COMPANY_B_APP_SECRETS="${WECOM_COMPANY_B_APP_SECRETS:-}"
WEDOC_COMPANY_B_DOCID="${WEDOC_COMPANY_B_DOCID:-}"
WEDOC_COMPANY_B_SHEET_ID="${WEDOC_COMPANY_B_SHEET_ID:-}"
WEDRIVE_COMPANY_B_SPACEIDS="${WEDRIVE_COMPANY_B_SPACEIDS:-}"
SMARTSHEET_COMPANY_B_ID="${SMARTSHEET_COMPANY_B_ID:-}"
SMARTSHEET_COMPANY_B_SHEET_ID="${SMARTSHEET_COMPANY_B_SHEET_ID:-}"
WECOM_DOC_ADMIN_USERS="${WECOM_DOC_ADMIN_USERS:-}"
WECOM_KF_CORP_ID="${WECOM_KF_CORP_ID:-${WECOM_COMPANY_B_CORP_ID:-}}"
WECOM_KF_APP_SECRET="${WECOM_KF_APP_SECRET:-}"
WECOM_KF_CALLBACK_TOKEN="${WECOM_KF_CALLBACK_TOKEN:-${WECOM_COMPANY_B_CALLBACK_TOKEN:-}}"
WECOM_KF_CALLBACK_AES_KEY="${WECOM_KF_CALLBACK_AES_KEY:-${WECOM_COMPANY_B_CALLBACK_AESKEY:-}}"
WECOM_KF_API_TIMEOUT_SECONDS="${WECOM_KF_API_TIMEOUT_SECONDS:-10}"
WECOM_KF_PROCESSOR_URL="${WECOM_KF_PROCESSOR_URL:-http://host.docker.internal:18080/v1/chat/completions}"
WECOM_KF_PROCESSOR_TIMEOUT_SECONDS="${WECOM_KF_PROCESSOR_TIMEOUT_SECONDS:-1260}"
OPENCLAW_INTERNAL_TOKEN="${OPENCLAW_INTERNAL_TOKEN:-}"
FEISHU_ENV_PROFILES="${FEISHU_ENV_PROFILES:-${FEISHU_ENV_PROFILE:-}}"
FEISHU_COMPANY_A_APP_ID="${FEISHU_COMPANY_A_APP_ID:-}"
FEISHU_COMPANY_A_APP_SECRET="${FEISHU_COMPANY_A_APP_SECRET:-}"
FEISHU_COMPANY_A_APP_TOKEN="${FEISHU_COMPANY_A_APP_TOKEN:-}"
FEISHU_COMPANY_A_TABLE_ID="${FEISHU_COMPANY_A_TABLE_ID:-}"
FEISHU_COMPANY_A_VIEW_ID="${FEISHU_COMPANY_A_VIEW_ID:-}"
FEISHU_COMPANY_A_WIKI_NODE_TOKEN="${FEISHU_COMPANY_A_WIKI_NODE_TOKEN:-}"
FEISHU_COMPANY_A_WIKI_URL="${FEISHU_COMPANY_A_WIKI_URL:-}"
FEISHU_COMPANY_A_APP_NAME="${FEISHU_COMPANY_A_APP_NAME:-}"
FEISHU_COMPANY_A_TABLE_NAME="${FEISHU_COMPANY_A_TABLE_NAME:-}"
FEISHU_SESSION_CONSOLE_APP_TOKEN="${FEISHU_SESSION_CONSOLE_APP_TOKEN:-}"
FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID="${FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID:-}"
FEISHU_SESSION_CONSOLE_TASK_TABLE_ID="${FEISHU_SESSION_CONSOLE_TASK_TABLE_ID:-}"
FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID="${FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID:-}"
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL="${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-}"
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME="${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN="${FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL="${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-}"
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME="${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-}"
FEISHU_COMPANY_B_APP_ID="${FEISHU_COMPANY_B_APP_ID:-}"
FEISHU_COMPANY_B_APP_SECRET="${FEISHU_COMPANY_B_APP_SECRET:-}"
FEISHU_COMPANY_B_APP_TOKEN="${FEISHU_COMPANY_B_APP_TOKEN:-}"
FEISHU_COMPANY_B_TABLE_ID="${FEISHU_COMPANY_B_TABLE_ID:-}"
FEISHU_COMPANY_B_VIEW_ID="${FEISHU_COMPANY_B_VIEW_ID:-}"
FEISHU_COMPANY_B_WIKI_NODE_TOKEN="${FEISHU_COMPANY_B_WIKI_NODE_TOKEN:-}"
FEISHU_COMPANY_B_WIKI_URL="${FEISHU_COMPANY_B_WIKI_URL:-}"
FEISHU_COMPANY_B_APP_NAME="${FEISHU_COMPANY_B_APP_NAME:-}"
FEISHU_COMPANY_B_TABLE_NAME="${FEISHU_COMPANY_B_TABLE_NAME:-}"
# Version-inventory weekly digest bot credentials. Standalone app, unrelated to
# the FEISHU_COMPANY_* bitable sync apps. Uses dedicated VERSION_DIGEST_* names
# (not FEISHU_APP_ID/FEISHU_APP_SECRET) so it can never be silently clobbered by
# the legacy openclaw fallback below, which sources /root/openclaw/.env and
# defines its own FEISHU_APP_ID/FEISHU_APP_SECRET for the COMPANY_A app.
VERSION_DIGEST_FEISHU_APP_ID="${VERSION_DIGEST_FEISHU_APP_ID:-}"
VERSION_DIGEST_FEISHU_APP_SECRET="${VERSION_DIGEST_FEISHU_APP_SECRET:-}"
VERSION_DIGEST_FEISHU_RECEIVE_ID="${VERSION_DIGEST_FEISHU_RECEIVE_ID:-}"
if [[ (-z "$FEISHU_COMPANY_A_APP_ID" || -z "$FEISHU_COMPANY_A_APP_SECRET" || -z "$FEISHU_SESSION_CONSOLE_APP_TOKEN" || -z "$FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID") && -f "/root/openclaw/.env" ]]; then
  # Reuse the existing Feishu self-built app credentials owned by OpenClaw.
  # The real secret values stay in the ECS-private /root/openclaw/.env file.
  # shellcheck disable=SC1091
  set -a
  source "/root/openclaw/.env"
  set +a
  FEISHU_ENV_PROFILES="${FEISHU_ENV_PROFILES:-COMPANY_A}"
  FEISHU_COMPANY_A_APP_ID="${FEISHU_COMPANY_A_APP_ID:-${FEISHU_APP_ID:-}}"
  FEISHU_COMPANY_A_APP_SECRET="${FEISHU_COMPANY_A_APP_SECRET:-${FEISHU_APP_SECRET:-}}"
fi
FEISHU_SESSION_CONSOLE_APP_TOKEN="${FEISHU_SESSION_CONSOLE_APP_TOKEN:-${FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN:-}}"
FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID="${FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID:-${FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID:-}}"
FEISHU_SESSION_CONSOLE_TASK_TABLE_ID="${FEISHU_SESSION_CONSOLE_TASK_TABLE_ID:-${FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID:-}}"
FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID="${FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID:-${FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID:-}}"
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL="${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-${FEISHU_CHATGPT_PROJECT_URL:-${FEISHU_COMPANY_A_CHATGPT_PROJECT_URL:-}}}}"
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME="${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-${FEISHU_CHATGPT_PROJECT_NAME:-${FEISHU_COMPANY_A_CHATGPT_PROJECT_NAME:-飞书 AI 会话台}}}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN="${FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN:-${FEISHU_SESSION_CONSOLE_APP_TOKEN:-}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID:-${FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID:-}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID:-${FEISHU_SESSION_CONSOLE_TASK_TABLE_ID:-}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID="${FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID:-${FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID:-}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL="${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL:-}}"
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME="${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME:-}}"
CHANJET_BASE_URL="${CHANJET_BASE_URL:-https://openapi.chanjet.com}"
CHANJET_APP_KEY="${CHANJET_APP_KEY:-}"
CHANJET_APP_SECRET="${CHANJET_APP_SECRET:-}"
CHANJET_OPEN_TOKEN="${CHANJET_OPEN_TOKEN:-}"
CHANJET_WEBHOOK_AES_KEY="${CHANJET_WEBHOOK_AES_KEY:-}"
CHANJET_CERTIFICATE="${CHANJET_CERTIFICATE:-}"
CHANJET_EVENT_SPOOL_DIR="${CHANJET_EVENT_SPOOL_DIR:-/tmp/aliecs-integration-events/chanjet}"
CHANJET_AUTO_EXCHANGE_OAUTH_CODE="${CHANJET_AUTO_EXCHANGE_OAUTH_CODE:-false}"
DEFAULT_PAGE_SIZE="${DEFAULT_PAGE_SIZE:-500}"
REQUEST_TIMEOUT_CONNECT="${REQUEST_TIMEOUT_CONNECT:-5}"
REQUEST_TIMEOUT_READ="${REQUEST_TIMEOUT_READ:-30}"
TPLUS_SYNC_INTERVAL_SECONDS="${TPLUS_SYNC_INTERVAL_SECONDS:-86400}"
TPLUS_BOM_WRITE_ENABLED="${TPLUS_BOM_WRITE_ENABLED:-false}"
RECIPE_ACTIVE_BOM_DIR="${RECIPE_ACTIVE_BOM_DIR:-/app/recipe-active-bom}"
OPS_HEALTH_HTTP_TARGETS_JSON="${OPS_HEALTH_HTTP_TARGETS_JSON:-}"
OPS_HEALTH_BACKEND_URL="${OPS_HEALTH_BACKEND_URL:-}"
OPS_HEALTH_PUBLIC_WEB_URL="${OPS_HEALTH_PUBLIC_WEB_URL:-}"
WEBDOCK_TUNNEL_PROXY_ENABLED="${WEBDOCK_TUNNEL_PROXY_ENABLED:-true}"
WEBDOCK_TUNNEL_PROXY_BIND_HOST="${WEBDOCK_TUNNEL_PROXY_BIND_HOST:-172.17.0.1}"
WEBDOCK_TUNNEL_PROXY_BIND_PORT="${WEBDOCK_TUNNEL_PROXY_BIND_PORT:-11800}"
WEBDOCK_TUNNEL_PROXY_TARGET_HOST="${WEBDOCK_TUNNEL_PROXY_TARGET_HOST:-127.0.0.1}"
WEBDOCK_TUNNEL_PROXY_TARGET_PORT="${WEBDOCK_TUNNEL_PROXY_TARGET_PORT:-11800}"
WEBDOCK_TUNNEL_PROXY_BACKLOG="${WEBDOCK_TUNNEL_PROXY_BACKLOG:-64}"

LOG_DIR="${DEPLOY_LOG_DIR:-$ROOT_DIR/logs}"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/deploy-$(date +%Y%m%d).log"
exec > >(tee -a "$LOG_FILE") 2>&1

if [[ "$STORAGE_DRIVER" == "webdock" && -z "$WEBDOCK_PHOTO_API_TOKEN" ]]; then
  echo "[部署] STORAGE_DRIVER=webdock 时必须在 release-meta.env 设置 WEBDOCK_PHOTO_API_TOKEN。" >&2
  exit 1
fi

mkdir -p "$METADATA_DIR"
CURRENT_ENV="$METADATA_DIR/current.env"
PREVIOUS_ENV="$METADATA_DIR/previous.env"

if [[ -f "$CURRENT_ENV" ]]; then
  cp "$CURRENT_ENV" "$PREVIOUS_ENV"
fi

# 每服务镜像标签：优先用调用方传入的内容寻址标签（*_TAG，内容没变 = 标签不变 = 容器不重建），
# 未提供时回落到 GitHub commit alias IMAGE_TAG；历史 v/V 标签仍可用于兼容回滚。
echo "[部署] 服务镜像标签：public-web=${PUBLIC_WEB_TAG:-$IMAGE_TAG} admin-ui=${ADMIN_UI_TAG:-$IMAGE_TAG} backend-api=${BACKEND_API_TAG:-$IMAGE_TAG} doc-sync-worker=${DOC_SYNC_WORKER_TAG:-$IMAGE_TAG} tplus-sync-worker=${TPLUS_SYNC_WORKER_TAG:-$IMAGE_TAG} mcp-coding-server=${MCP_CODING_SERVER_TAG:-$IMAGE_TAG}"

cat > "$CURRENT_ENV" <<ENV
PUBLIC_WEB_IMAGE=${GHCR_BASE}/public-web:${PUBLIC_WEB_TAG:-$IMAGE_TAG}
ADMIN_UI_IMAGE=${GHCR_BASE}/admin-ui:${ADMIN_UI_TAG:-$IMAGE_TAG}
BACKEND_API_IMAGE=${GHCR_BASE}/backend-api:${BACKEND_API_TAG:-$IMAGE_TAG}
DOC_SYNC_WORKER_IMAGE=${GHCR_BASE}/doc-sync-worker:${DOC_SYNC_WORKER_TAG:-$IMAGE_TAG}
TPLUS_SYNC_WORKER_IMAGE=${GHCR_BASE}/tplus-sync-worker:${TPLUS_SYNC_WORKER_TAG:-$IMAGE_TAG}
MCP_CODING_SERVER_IMAGE=${GHCR_BASE}/mcp-coding-server:${MCP_CODING_SERVER_TAG:-$IMAGE_TAG}

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}

AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET}
AUTH_TOKEN_TTL_SECONDS=${AUTH_TOKEN_TTL_SECONDS}
LOCAL_LOGIN_ENABLED=${LOCAL_LOGIN_ENABLED:-true}
MINIAPP_SERVICE_TOKEN=${MINIAPP_SERVICE_TOKEN:-}
QUALITY_WEBDAV_01_URL=${QUALITY_WEBDAV_01_URL:-https://dav.jianguoyun.com/dav/}
QUALITY_WEBDAV_01_USER=${QUALITY_WEBDAV_01_USER:-}
QUALITY_WEBDAV_01_PASS=${QUALITY_WEBDAV_01_PASS:-}
QUALITY_REPORT_MAX_UPLOAD_MB=${QUALITY_REPORT_MAX_UPLOAD_MB:-25}
BACKUP_REPORT_TOKEN=${BACKUP_REPORT_TOKEN:-}
VERSION_DIGEST_FEISHU_APP_ID=${VERSION_DIGEST_FEISHU_APP_ID:-}
VERSION_DIGEST_FEISHU_APP_SECRET=${VERSION_DIGEST_FEISHU_APP_SECRET:-}
VERSION_DIGEST_FEISHU_RECEIVE_ID=${VERSION_DIGEST_FEISHU_RECEIVE_ID:-}
EXECUTOR_BASE_URL=${EXECUTOR_BASE_URL}
EXECUTOR_TOKEN=${EXECUTOR_TOKEN}
EXECUTOR_TIMEOUT_SECONDS=${EXECUTOR_TIMEOUT_SECONDS}
ADMIN_BOOTSTRAP_USERNAME=${ADMIN_BOOTSTRAP_USERNAME}
ADMIN_BOOTSTRAP_PASSWORD=${ADMIN_BOOTSTRAP_PASSWORD}
ADMIN_BOOTSTRAP_DISPLAY_NAME=${ADMIN_BOOTSTRAP_DISPLAY_NAME}
COUPLE_FEATURE_ENABLED=${COUPLE_FEATURE_ENABLED}
COUPLE_ROUTE=${COUPLE_ROUTE}
COUPLE_ALLOWED_USERS=${COUPLE_ALLOWED_USERS}
COUPLE_ALLOWED_EMAILS=${COUPLE_ALLOWED_EMAILS}
APP_BASE_URL=${APP_BASE_URL}
SHARE_BASE_URL=${SHARE_BASE_URL}
STORAGE_DRIVER=${STORAGE_DRIVER}
MAX_UPLOAD_MB=${MAX_UPLOAD_MB}
WEBDOCK_PHOTO_BASE_URL=${WEBDOCK_PHOTO_BASE_URL}
WEBDOCK_PHOTO_API_TOKEN=${WEBDOCK_PHOTO_API_TOKEN}
WEBDOCK_PHOTO_TIMEOUT_SECONDS=${WEBDOCK_PHOTO_TIMEOUT_SECONDS}
IMMICH_ENABLED=${IMMICH_ENABLED}
IMMICH_BASE_URL=${IMMICH_BASE_URL}
IMMICH_API_KEY=${IMMICH_API_KEY}
IMMICH_TIMEOUT_SECONDS=${IMMICH_TIMEOUT_SECONDS}
IMMICH_PROXY_MODE=${IMMICH_PROXY_MODE}
WECOM_ENV_PROFILES=${WECOM_ENV_PROFILES}
WECOM_COMPANY_A_CORP_ID=${WECOM_COMPANY_A_CORP_ID}
WECOM_COMPANY_A_APP_SECRET=${WECOM_COMPANY_A_APP_SECRET}
WECOM_COMPANY_A_APP_SECRET_2=${WECOM_COMPANY_A_APP_SECRET_2}
WECOM_COMPANY_A_APP_SECRETS=${WECOM_COMPANY_A_APP_SECRETS}
WEDOC_COMPANY_A_DOCID=${WEDOC_COMPANY_A_DOCID}
WEDOC_COMPANY_A_SHEET_ID=${WEDOC_COMPANY_A_SHEET_ID}
WEDRIVE_COMPANY_A_SPACEIDS=${WEDRIVE_COMPANY_A_SPACEIDS}
SMARTSHEET_COMPANY_A_ID=${SMARTSHEET_COMPANY_A_ID}
SMARTSHEET_COMPANY_A_SHEET_ID=${SMARTSHEET_COMPANY_A_SHEET_ID}
WECOM_COMPANY_B_CORP_ID=${WECOM_COMPANY_B_CORP_ID}
WECOM_COMPANY_B_APP_SECRET=${WECOM_COMPANY_B_APP_SECRET}
WECOM_COMPANY_B_APP_SECRET_2=${WECOM_COMPANY_B_APP_SECRET_2}
WECOM_COMPANY_B_APP_SECRETS=${WECOM_COMPANY_B_APP_SECRETS}
WECOM_COMPANY_B_APPROVAL_SECRET=${WECOM_COMPANY_B_APPROVAL_SECRET:-}
WECOM_COMPANY_B_GROUPBOT_ID=${WECOM_COMPANY_B_GROUPBOT_ID:-}
WECOM_COMPANY_B_GROUPBOT_SECRET=${WECOM_COMPANY_B_GROUPBOT_SECRET:-}
WEDOC_COMPANY_B_DOCID=${WEDOC_COMPANY_B_DOCID}
WEDOC_COMPANY_B_SHEET_ID=${WEDOC_COMPANY_B_SHEET_ID}
WEDRIVE_COMPANY_B_SPACEIDS=${WEDRIVE_COMPANY_B_SPACEIDS}
SMARTSHEET_COMPANY_B_ID=${SMARTSHEET_COMPANY_B_ID}
SMARTSHEET_COMPANY_B_SHEET_ID=${SMARTSHEET_COMPANY_B_SHEET_ID}
WECOM_DOC_ADMIN_USERS=${WECOM_DOC_ADMIN_USERS}
WECOM_KF_CORP_ID=${WECOM_KF_CORP_ID}
WECOM_KF_APP_SECRET=${WECOM_KF_APP_SECRET}
WECOM_KF_CALLBACK_TOKEN=${WECOM_KF_CALLBACK_TOKEN}
WECOM_KF_CALLBACK_AES_KEY=${WECOM_KF_CALLBACK_AES_KEY}
WECOM_KF_API_TIMEOUT_SECONDS=${WECOM_KF_API_TIMEOUT_SECONDS}
WECOM_KF_PROCESSOR_URL=${WECOM_KF_PROCESSOR_URL}
WECOM_KF_PROCESSOR_TIMEOUT_SECONDS=${WECOM_KF_PROCESSOR_TIMEOUT_SECONDS}
OPENCLAW_INTERNAL_TOKEN=${OPENCLAW_INTERNAL_TOKEN}
FEISHU_ENV_PROFILES=${FEISHU_ENV_PROFILES}
FEISHU_COMPANY_A_APP_ID=${FEISHU_COMPANY_A_APP_ID}
FEISHU_COMPANY_A_APP_SECRET=${FEISHU_COMPANY_A_APP_SECRET}
FEISHU_COMPANY_A_APP_TOKEN=${FEISHU_COMPANY_A_APP_TOKEN}
FEISHU_COMPANY_A_TABLE_ID=${FEISHU_COMPANY_A_TABLE_ID}
FEISHU_COMPANY_A_VIEW_ID=${FEISHU_COMPANY_A_VIEW_ID}
FEISHU_COMPANY_A_WIKI_NODE_TOKEN=${FEISHU_COMPANY_A_WIKI_NODE_TOKEN}
FEISHU_COMPANY_A_WIKI_URL=${FEISHU_COMPANY_A_WIKI_URL}
FEISHU_COMPANY_A_APP_NAME=${FEISHU_COMPANY_A_APP_NAME}
FEISHU_COMPANY_A_TABLE_NAME=${FEISHU_COMPANY_A_TABLE_NAME}
FEISHU_SESSION_CONSOLE_APP_TOKEN=${FEISHU_SESSION_CONSOLE_APP_TOKEN}
FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID=${FEISHU_SESSION_CONSOLE_MESSAGE_TABLE_ID}
FEISHU_SESSION_CONSOLE_TASK_TABLE_ID=${FEISHU_SESSION_CONSOLE_TASK_TABLE_ID}
FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID=${FEISHU_SESSION_CONSOLE_SESSION_TABLE_ID}
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL=${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_URL}
FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME=${FEISHU_SESSION_CONSOLE_CHATGPT_PROJECT_NAME}
FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN=${FEISHU_COMPANY_A_SESSION_CONSOLE_APP_TOKEN}
FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID=${FEISHU_COMPANY_A_SESSION_CONSOLE_MESSAGE_TABLE_ID}
FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID=${FEISHU_COMPANY_A_SESSION_CONSOLE_TASK_TABLE_ID}
FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID=${FEISHU_COMPANY_A_SESSION_CONSOLE_SESSION_TABLE_ID}
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL=${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_URL}
FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME=${FEISHU_COMPANY_A_SESSION_CONSOLE_CHATGPT_PROJECT_NAME}
FEISHU_COMPANY_B_APP_ID=${FEISHU_COMPANY_B_APP_ID}
FEISHU_COMPANY_B_APP_SECRET=${FEISHU_COMPANY_B_APP_SECRET}
FEISHU_COMPANY_B_APP_TOKEN=${FEISHU_COMPANY_B_APP_TOKEN}
FEISHU_COMPANY_B_TABLE_ID=${FEISHU_COMPANY_B_TABLE_ID}
FEISHU_COMPANY_B_VIEW_ID=${FEISHU_COMPANY_B_VIEW_ID}
FEISHU_COMPANY_B_WIKI_NODE_TOKEN=${FEISHU_COMPANY_B_WIKI_NODE_TOKEN}
FEISHU_COMPANY_B_WIKI_URL=${FEISHU_COMPANY_B_WIKI_URL}
FEISHU_COMPANY_B_APP_NAME=${FEISHU_COMPANY_B_APP_NAME}
FEISHU_COMPANY_B_TABLE_NAME=${FEISHU_COMPANY_B_TABLE_NAME}
CHANJET_BASE_URL=${CHANJET_BASE_URL}
CHANJET_APP_KEY=${CHANJET_APP_KEY}
CHANJET_APP_SECRET=${CHANJET_APP_SECRET}
CHANJET_OPEN_TOKEN=${CHANJET_OPEN_TOKEN}
CHANJET_WEBHOOK_AES_KEY=${CHANJET_WEBHOOK_AES_KEY}
CHANJET_CERTIFICATE=${CHANJET_CERTIFICATE}
CHANJET_EVENT_SPOOL_DIR=${CHANJET_EVENT_SPOOL_DIR}
CHANJET_AUTO_EXCHANGE_OAUTH_CODE=${CHANJET_AUTO_EXCHANGE_OAUTH_CODE}
DEFAULT_PAGE_SIZE=${DEFAULT_PAGE_SIZE}
REQUEST_TIMEOUT_CONNECT=${REQUEST_TIMEOUT_CONNECT}
REQUEST_TIMEOUT_READ=${REQUEST_TIMEOUT_READ}
TPLUS_SYNC_INTERVAL_SECONDS=${TPLUS_SYNC_INTERVAL_SECONDS}
TPLUS_BOM_WRITE_ENABLED=${TPLUS_BOM_WRITE_ENABLED}
RECIPE_ACTIVE_BOM_DIR=${RECIPE_ACTIVE_BOM_DIR}
OPS_HEALTH_HTTP_TARGETS_JSON=${OPS_HEALTH_HTTP_TARGETS_JSON}
OPS_HEALTH_BACKEND_URL=${OPS_HEALTH_BACKEND_URL}
OPS_HEALTH_PUBLIC_WEB_URL=${OPS_HEALTH_PUBLIC_WEB_URL}
OIDC_ENABLED=${OIDC_ENABLED:-false}
OIDC_ISSUER=${OIDC_ISSUER:-}
OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-}
OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-}
OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI:-}
ENV

cp "$CURRENT_ENV" "$RUNTIME_ENV_FILE"

if [[ "$WEBDOCK_TUNNEL_PROXY_ENABLED" == "true" ]]; then
  echo "[部署] 配置 WebDock SSH 隧道容器代理"
  "$ROOT_DIR/install-webdock-tunnel-proxy.sh"
fi

if [[ "${IMMICH_TUNNEL_PROXY_ENABLED:-false}" == "true" ]]; then
  echo "[部署] 配置 Immich SSH 隧道容器代理"
  "$ROOT_DIR/install-immich-tunnel-proxy.sh"
fi

if [[ -n "${GHCR_USERNAME:-}" && -n "${GHCR_TOKEN:-}" ]]; then
  echo "[部署] 登录 GHCR"
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
fi

echo "[部署] 拉取镜像（逐服务串行，避免并行解压打爆 2G 内存，见 2026-06-10 OOM 假死事故）"
pull_failed=0
for service in $(docker compose --env-file "$RUNTIME_ENV_FILE" -f "$COMPOSE_FILE" config --services); do
  echo "[部署] 拉取 $service"
  if ! docker compose --env-file "$RUNTIME_ENV_FILE" -f "$COMPOSE_FILE" pull "$service"; then
    pull_failed=1
    break
  fi
done
if [[ "$pull_failed" -ne 0 ]]; then
  echo "[部署] 拉取镜像失败。若报 unauthorized，请检查：" >&2
  echo "[部署] 1) GHCR 包可见性（public/private）" >&2
  echo "[部署] 2) GHCR_USERNAME / GHCR_TOKEN 是否在 ECS 或 Actions 中正确提供" >&2
  echo "[部署] 3) GHCR_BASE 与镜像命名是否一致（例如 ghcr.io/huozao/*）" >&2
  exit 1
fi

# 迁移条件化：db/ 与 migrate.sh 自上次成功部署未变更时跳过（省 2G 小机上的数分钟）。
# 判定不了就保守执行；FORCE_MIGRATIONS=1 强制执行。
REPO_ROOT="$(cd "$ROOT_DIR/../.." && pwd)"
LAST_SUCCESS_COMMIT_FILE="$METADATA_DIR/last-success-commit"
RUN_MIGRATIONS="${FORCE_MIGRATIONS:-}"
if [[ -z "$RUN_MIGRATIONS" ]]; then
  RUN_MIGRATIONS=1
  if [[ -f "$LAST_SUCCESS_COMMIT_FILE" ]] && git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    last_success="$(cat "$LAST_SUCCESS_COMMIT_FILE")"
    if git -C "$REPO_ROOT" cat-file -e "${last_success}^{commit}" 2>/dev/null \
      && git -C "$REPO_ROOT" diff --quiet "$last_success" HEAD -- db deploy/ecs/migrate.sh; then
      RUN_MIGRATIONS=0
    fi
  fi
fi
if [[ "$RUN_MIGRATIONS" == "1" ]]; then
  echo "[部署] 先执行迁移"
  "$ROOT_DIR/migrate.sh"
else
  echo "[部署] db/ 与 migrate.sh 自上次成功部署（$(cat "$LAST_SUCCESS_COMMIT_FILE")）未变更，跳过迁移"
fi

echo "[部署] 再切换服务"
docker compose --env-file "$RUNTIME_ENV_FILE" -f "$COMPOSE_FILE" up -d

if "$ROOT_DIR/healthcheck.sh"; then
  if git -C "$REPO_ROOT" rev-parse HEAD >/dev/null 2>&1; then
    git -C "$REPO_ROOT" rev-parse HEAD > "$LAST_SUCCESS_COMMIT_FILE"
  fi
  "$ROOT_DIR/write-deployment-manifest.sh"
  echo "[部署] 成功"
  exit 0
fi

echo "[部署] 失败，开始回滚"
"$ROOT_DIR/rollback.sh"
exit 1
